### ISSUE TITLE
[Bug] crash on start if config setting is "enableIncubator : false"

### ISSUE THREAD

**Issue by MilkissWhite** [melontini/m-tweaks#10]
**Describe the bug**
if my "enableIncubator" setting is "false", game crash on start.

**To Reproduce**
1. Set config setting to "enableIncubator : false"
2. Start launcher and push start button
3. game crash and you can See error message

**Expected behavior**
game normally start and incubator is not able to use

**Screenshots**
not screenshot but this is error message : 
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'm-tweaks'!

**Logs**
sorry, I don't know where my log file when I using CurseForge App...
instead, I put here my "m-tweaks.json" config file.
[m-tweaks.zip](https://github.com/melontini/m-tweaks/files/10831921/m-tweaks.zip)

**Environment:**
 - Minecraft Version [1.19.3]
 - Mod Version [0.4.11-1.19.3]
 - Fabric [0.14.13]
 - Fabric API [0.74.0+1.19.3]
 - Cloth Config API [9.0.94-fabric]

**Additional context**
I tested with "compatMode" true/false both, and it was same error.
I also "incubatorRandomness" true/false both(with each "compatMode" true/false), and it was same error.

**Comment by melontini** [comment]
I identified the issue, this need to be fixed in [CrackerUtil](https://github.com/melontini/cracker-util)
