### ISSUE TITLE
[Suggestion] Throwability

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#14]
**Is your feature request related to a problem? Please describe.**
Sometimes my inventory is filled up with low quality items, and I have to clean the inventory from time to time. There're so many things considered to be "garbage", such as ink sacs ( sometimes even the glowing one), flowers and saplings. But it's a little bit rude to drop them into lava or just leave them on the ground. Why not making them throwable? 

**Describe the solution you'd like**
Make several items throwable, spawn particles on hit and give effect based on what you've thrown. ( e.g. red dyes spawn red particles, ink sacs blind target, saplings being planted on hitting dirt). 

**Describe alternatives you've considered**
Those features may be hard to accomplish so I placed them here. 
1. Customizable items, particles and effects ( e.g. kubejs:abc, minecraft:dragon_breath, minecraft:poison).
2. Dye target block/entity temporarily in configurable radius. 

**Additional context**
Idk whether it's a good idea or something breaking the "vanilla feeling", it's just for fun.

**Comment by melontini** [comment]
Since you mention KubeJS. One of my other mods allows adding behaviors via KubeJS's reflection. [link](https://github.com/melontini/good-tea/wiki/Adding-custom-behaviors-with-KubeJS)

I can add a similar feature here. This allows for more complex things than just effects.

**Comment by Rad233** [comment]
> Something like this?
> 
>  what.mp4

yep

**Comment by melontini** [comment]
So, uh....

https://user-images.githubusercontent.com/104443436/233850602-a20ef25e-3f6e-4bb8-a4d7-b7e895ca9d73.mp4

**Comment by Rad233** [comment]
> 

Bruh😳 Is this shown on the screen when player got hit?

**Comment by melontini** [comment]
Yes

**Comment by Rad233** [comment]
> 



> Yes

Hmm, defidefinitely they would get mad. What about ink effect ( with fade out animation)? https://pixabay.com/zh/illustrations/watercolor-watercolour-elegant-4629348/

**Comment by Rad233** [comment]
[effects.zip](https://github.com/melontini/m-tweaks/files/11306738/effects.zip)
I drew these particle effects originally for enhanced visuals(but didn't really used this mod), but I guess they might help.

**Comment by Rad233** [comment]
> > > 
> > 
> > 
> > > Yes
> > 
> > 
> > Hmm, defidefinitely they would get mad. What about ink effect ( with fade out animation)? https://pixabay.com/zh/illustrations/watercolor-watercolour-elegant-4629348/
> 
> I think I'll leave it as vanilla blindness for now. I'll probably add something like this later.

Cool!

**Comment by melontini** [comment]
I've updated the wiki to include throwable items. I hope that Adding Custom Behaviors is clear enough 😅

https://github.com/melontini/m-tweaks/wiki/4.Item-tweaks#throwable-items--050

**Comment by Rad233** [comment]
1. I tried override vanilla snowball behavior by turning complement false, but it still behaves vanilla. Could you give me a simple example of that option? 
2. It would be better if I can customize each item's cooldown ( for blocks, it cant be placed when it's in cooldown). 
3. Gunpowder is too loud, it triggers only a small explosion but sounds like a normal tnt. 
4. All the throwable items I added could't damage entities, one possible way using command is summoning a invisible creeper, but it's completely diffierent from damaging directly. What about adding a "can_damage" option? 
5. Fire charge sound is only triggered when player holding it and right clicking a block.

**Comment by melontini** [comment]
Ah, so I can answer a few of those.

1. This is because I inject item logic after vanilla, and the logic is only triggered if the previous action returned `PASS`. I did this because of items like Fire Charge that have different behaviors.
2. Sure, I wanted to add something like this, but the first solution I came up with wasn't very good. It will probably be part of the item behavior datapack.
3. I don't think there's any way to change this, since it's the vanilla behavior for all explosions.
4. I thought there was a `damage` command. I'll look into it.
5. Someone forgot to add sounds to items 💀.

**Comment by Rad233** [comment]
I tried modifying some dyes but some of them are not working ( black, brown, cyan, blue). Here's black_dye.json: 
{
  "item_id": "minecraft:black_dye",
  "complement": true,
  "spawn_colored_particles": true,
  "particle_colors": {
    "red": 5,
    "green": 5,
    "blue": 8
  },
  "on_block_hit": {
    "hit_block_commands": [
      "say 1"
    ]
  }
}
It should say 1 in chat, but it's not working. Other dyes work fine, though.

**Comment by melontini** [comment]
Well, I know what I'll be doing this weekend.

Currently, collisions aren't handled very well, so as a patchwork, you can try putting your dye logic into `data\m-tweaks\mt_item_throw_behavior` (I assume you're using KubeJS to load data). This should overwrite the default behavior, I think.

But I definitely need a better way to load datapacks than a HashMap.

**Comment by Rad233** [comment]
[Throwable item+.zip](https://github.com/melontini/m-tweaks/files/11384624/Throwable.item%2B.zip)
I made this datapack to expand the throwable items. It contains throwable crops, scaffoldings, cobweb... Some of them are just for fun so I didn't submit a pull request.

**Comment by melontini** [comment]
So, I think the next update should address a bunch of these things.

* I added `override_vanilla` to allow blocking vanilla behaviors.
* You can now specify `cooldown` (in ticks) in your datapack.
* I backported the damage command. Mojang changed DamageSource in 1.19.4, so this isn't a 1-1 port.

Also, a random, but probably useful change is `item_id` now accepts arrays of IDs. e.g.

```json
{
  "item_id": [
    "cobblestone",
    "tuff",
    "dripstone_block",
    "stone",
    "granite"
  ],
  "on_entity_hit": {
    "hit_entity_commands": [
      "/damage @s 10"
    ]
  }
}
```

**Comment by Rad233** [comment]
> So, I think this update should address a bunch of these things.
> 
> * I added `override_vanilla` to allow blocking vanilla behaviors.
> * You can now specify `cooldown` (in ticks) in your datapack.
> * I backported the damage command. Mojang changed DamageSource in 1.19.4, so this isn't a 1-1 port.
> 
> Also, a random, but probably useful change is `item_id` now accepts arrays of IDs. e.g.

Huge thanks! These features would be so useful! btw, do you have a ko-fi account ( idk how to use crypto)?
