### ISSUE TITLE
[Bug]: Flickering dye blinding with Exordium

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#18]
### What happened?

When installed with exordium, the color blinding flickers when shown along with gui. ( edit: gui particles the same)
Turning off `enabledScreens` in exordium config solves this issue. 
Actually it's not a issue of m-tweaks, it was just what exordium does ( limiting gui fps). So I think these two mods are sadly incompatible in some ways.

### Mod Version

0.5.2

### Minecraft Version

- [X] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3

**Comment by melontini** [comment]
I guess this falls under `Many other mods that render their own GUI elements, the wilder the mod, the more likely it is to not work with this mod.` category. Probably nothing I can really do, as this is exactly what's happening here.
