### ISSUE TITLE
[Suggestion] Dark mode for m-tweaks

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#19]
**Is your feature request related to a problem? Please describe.**
Dark mode looks good.

**Describe the solution you'd like**
Add a built-in optional resourcepack. Dark mode guis are prepared below: 
![fletching](https://user-images.githubusercontent.com/99306685/237055141-81303e5d-5ca7-4c52-b07a-78925a48ebc5.png)
![wiki_button](https://user-images.githubusercontent.com/99306685/237055170-35199777-32be-4053-acfe-b09f6ec5f4bd.png)

**Additional context**
I made these images myself and there are no limitations using them.

**Comment by melontini** [comment]
Done in next version.
