### ISSUE TITLE
[Bug]: Screen effects "stuck" on the screen

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#20]
### What happened?

Gui particles stay on the screen even after the gui was closed, making it "stuck" ( shake with camera) on the screen until it disappears. 

### Screenshots

https://github.com/melontini/m-tweaks/assets/99306685/fcd87e98-05c8-4db6-9d5b-03431a30e0e7

### Mod Version

0.5.2

### Minecraft Version

- [X] 1.18.2
- [ ] 1.19.x
- [ ] 1.19.3

**Comment by melontini** [comment]
Fixed in 0.5.3

**Comment by Rad233** [comment]
wait, furnace particles wasnt fixed
