### ISSUE TITLE
Unable to turn off campfire feature

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#3]
Mod version: 0.4.1-1.18.2
Game version: 1.18.2 fabric
Description: Can't turn off campfire feature, everytime I restart the game, it automatically turns back to the default(true) value.

**Comment by melontini** [comment]
I think I fixed it! New version should be up by now.

**Comment by Rad233** [comment]
> I think I fixed it! New version should be up by now.

Now can't enable compat mode(crash)💀
