### ISSUE TITLE
[Bug] infinite title screen reloading (0.4.8-1.19.3)

### ISSUE THREAD

**Issue by MilkissWhite** [melontini/m-tweaks#7]
**Describe the bug**
minecraft repeatly reload(looks like changing resource pack) at title screen, while all text are glitched to squere shape. so basically you can not click any button because of reloading process.

**To Reproduce**
1. Start minecraft at launcher
2. Bug start

**Environment:**
 - Minecraft [1.19.3]
 - Fabric [0.14.13]
 - Curseforge app [v.0.218.1.8323]
 - m-tweaks [0.4.8-1.19.3]
 - Cloth Config API (Fabric/Forge) [9.0.94-fabric]
 - Fabric API [0.73.2+1.19.3]
 - Playing with Korean language

**Additional context**
not happening while using m-tweaks version [0.4.7-1.19.3] (alpha)

**Comment by melontini** [comment]
I've asked the game really nicely, so [this build](https://github.com/melontini/m-tweaks/actions/runs/4209961091) might even work.

**Comment by MilkissWhite** [comment]
tested 0.4.9-1.19.3 version and it has same bug still.

**Comment by melontini** [comment]
I can't seem to reproduce it. Can you please send me the log?

**Comment by Bartosz417** [comment]
Currently have the same issue, narrowed it down to this. Menu screen has squares instead of letters, and does the exact thing as above. Does not conflict with anything as even launching it alone same thing happens. Got the logs which tell quite a bit about the error, but no idea how to paste them in here without filling a few pages.

**Comment by melontini** [comment]
Hi, you can drag & drop latest.log when replying. It should get uploaded to GitHub as a file.

**Comment by melontini** [comment]
I have a feeling the error is either about "missing texture list for knockoff totem particles" or "redundant texture list for knockoff totem particles"

**Comment by Bartosz417** [comment]
Caused by: java.lang.IllegalStateException: Redundant texture list for particle m-tweaks:knockoff_totem_particles
[Render thread/ERROR] Error saving option GUI Scale: DynamicException[Value 4 outside of range [0:3] Optional[4]]
putting this up as I saved it earlier while i get mc up again

**Comment by Bartosz417** [comment]
https://paste.atlauncher.com/view/0865b53c-531c-4d09-9db9-32685b63f789
gave me straight link from ATL

**Comment by melontini** [comment]
So, I figured out what the problem was.
It was me being stupid.

```java
 if (Tweaks.CONFIG.totemSettings.enableInfiniteTotem) //<- this if statement is the cause.
            Registry.register(Registries.PARTICLE_TYPE, new Identifier(MODID, "knockoff_totem_particles"), KNOCKOFF_TOTEM_PARTICLE);
```

Because I forgot to remove it, the game didn't register the particle, but still tried to register its factory, even if “infinite totem of undying” was disabled

```java
    @Inject(at = @At("TAIL"), method = "registerDefaultFactories")
    private void registerMTweaksFactories(CallbackInfo ci) {
        this.registerFactory(Tweaks.KNOCKOFF_TOTEM_PARTICLE, KnockoffTotemParticle.Factory::new);
    }
```

New patch coming lol.
